title: 原根 - Primitive root
description: <h1>求解原根的数学和编程</h1><p><div style="display:none;">	<script type="text/javascript" src="https://s4.cnzz.com/z_stat.php?id=1277931924&web_id=1277931924"></script></div></p>
show_downloads: true
lang: zh-CN
author:
  name: ZXC
theme: jekyll-theme-minimal
