title: 原根 - Primitive root
description: 求解原根的数学和编程<div style="display:none;">	<script type="text/javascript" src="https://s4.cnzz.com/z_stat.php?id=1277931924&web_id=1277931924"></script></div>
show_downloads: true
lang: zh-CN
theme: jekyll-theme-minimal
