title: 原根 - Primitive root
description: <h1>求解原根的数学和编程</h1><p><div style="display:none;">	<script type="text/javascript" src="https://s4.cnzz.com/z_stat.php?id=1277931924&web_id=1277931924"></script></div></p><p>（三）市场监管总局认为有必要直接查处或者指定有关
省级市场监管部门查处的涉嫌垄断协议行为。
省级市场监管部门发现涉嫌垄断协议行为属于市场监
管总局查处范围，或者属于本机构查处范围，但有必要由市
场监管总局查处的，应当及时就有关情况向市场监管总局报
告。</p>
show_downloads: true
lang: zh-CN
author:
  name: ZXC
theme: jekyll-theme-minimal
